version: '3'

services:

  mvp_metric:
    build: .
    image: simpleapi:latest
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
      uvicorn app.main:app --host 0.0.0.0 --port 5057"
    env_file:
      - .env
    ports:
      - "5057:5057"
    depends_on:
      - db_mvp_metric

  db_mvp_metric:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "12100:5432"

volumes:
  pg_data_mvp_metric: