version: '3'

services:

  db_mvp_metric:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - pg_data_mvp_metric:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "12100:5432"

volumes:
  pg_data_mvp_metric: